# Generated by Django 4.1.7 on 2023-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_comment_rating_watchlist_rename_cast_movie_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
