# Generated by Django 4.1.7 on 2023-04-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0006_remove_movie_actor_movie_actors_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
