# Generated by Django 4.1.7 on 2023-04-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0007_movie_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movies',
        ),
    ]
