# Generated by Django 4.1.7 on 2023-04-09 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0008_remove_genre_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='HomeApp.genre'),
        ),
    ]
