# Generated by Django 4.1.7 on 2023-04-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0009_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movies',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='HomeApp.movie'),
        ),
    ]
