# Generated by Django 4.1.7 on 2023-04-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0010_remove_watchlist_movie_watchlist_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='movies',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movies',
            field=models.ManyToManyField(related_name='watchlists', to='HomeApp.movie'),
        ),
    ]
