# Generated by Django 4.1.7 on 2023-04-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0011_remove_watchlist_movies_watchlist_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='HomeApp.genre'),
        ),
    ]
