# Generated by Django 4.1.7 on 2023-06-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0017_alter_rating_rating_alter_rating_user'),
        ('HomeApp', '0017_userprofile'),
    ]

    operations = [
    ]
